### ISSUE TITLE
Question about the code of schema linking

### ISSUE THREAD

**Issue by dannalily** [rhythmcao/text2sql-lgesql#10]
Hi there! Thanks for sharing the code of your interesting paper!

![image](https://user-images.githubusercontent.com/39847023/145913940-55c0cf9e-ba94-473f-af21-baebda12510d.png)

In line 253:  

> q_tab_mat = np.array([['question-table-nomatch'] * t_num for _ in range(q_num)], dtype=dtype)

It built 'q_tab_mat' with size (q_num, t_num), t_num is the length of 'table_token' . 

But in line 263:  

> q_tab_mat[range(i, j), idx] = 'question-table-exactmatch' 

the 'idx' refers to the index of 'table_name' rather than of 'table_token'.  

Could I ask why we should build q_tab_mat with the size of table_token but assign its value with the index of table_name?

**Comment by rhythmcao** [comment]
In this code snippet, table_toks/column_toks is a data structure like:

    [
        ['student', 'name'],
        ['course', 'name'],
        ['department', 'info'],
        ....
    ]

It means ``t_num = len(table_toks)`` is exactly the total number of tables in a specific database.
In other words, table_toks/column_toks is just a tokenized version of each schema item in table_names/column_names.

**Comment by dannalily** [comment]
I see. Thank you so much!
