### ISSUE TITLE
How I can do inference on the model only with a question?

### ISSUE THREAD

**Issue by ibs9668** [rhythmcao/text2sql-lgesql#24]
Hi, I want to know if is possible to use the model to get directly the SQL statment, after giving it a question in natural language. only use "Database  + Question"  like the picture
Thank you for help.
<img width="481" alt="image" src="https://user-images.githubusercontent.com/31496735/226782924-e10349a7-0043-48dc-8dc9-f50d66a24b36.png">

**Comment by FYWinds** [comment]
Did you figure out how to achieve that?
