### ISSUE TITLE
vocab.txt for GloVe

### ISSUE THREAD

**Issue by perused** [rhythmcao/text2sql-lgesql#7]
There appear to be inconsistencies between the vocabulary contained within vocab.txt used for GloVe embeddings and the actual vocabulary of the Spider dataset. In terms of unique words, there is no correlation between vocab.txt and the amount of unique words seen in only questions, only queries and questions + queries combined from the Spider dataset.

![image](https://user-images.githubusercontent.com/51703362/132939971-5794c230-c077-441a-8c0f-0bb6a8619494.png)

Furthermore, when I order the contents of each by frequencies, vocab.txt does not appear to match frequencies of the Spider dataset either. 

![image](https://user-images.githubusercontent.com/51703362/132939998-4f38db9b-94d2-42ab-8924-41b0df839068.png)

Since my investigations have yielded no conclusions, what is the meaning of vocab.txt? Where do the words and frequencies actually come from, if not the Spider dataset?

Note, I downloaded vocab.txt from the download link on the Code page: https://drive.google.com/file/d/1L8sWlp7J9LWjw9MP2bHGsf0wC4xLAyxO/view

**Comment by rhythmcao** [comment]
1. Please see run/run_preprocessing.sh for reference. There should be one script ``python3 -u preprocess/build_glove_vocab.py ...". It tells you exactly how to construct the vocab.txt for Glove. That's where our vocab.txt file comes from.
2. BTW, we use grammar-based decoder, therefore the query tokens such as t1, = and select are not included in the vocab.txt.

**Comment by perused** [comment]
Ah I see, I should have checked there before asking, thank you. 

And thank you for mentioning the decoder as well. I had included the query tokens as I was seeing if there was any similarity to vocab.txt between the two (evidently there was not).
